// <auto-generated />
using System;
using APM.StaffZen.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APM.StaffZen.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260316000001_AddWorkSchedulesTable")]
    partial class AddWorkSchedulesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APM.StaffZen.API.Models.Employee", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("CountryCode").HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("DateOfBirth").HasColumnType("datetime2");
                    b.Property<string>("Email").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("FcmToken").HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsOnboarded").HasColumnType("bit").HasDefaultValue(false);
                    b.Property<string>("FullName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int?>("GroupId").HasColumnType("int");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<int?>("OrganizationId").HasColumnType("int");
                    b.Property<string>("MobileNumber").HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("PasswordResetExpiry").HasColumnType("datetime2");
                    b.Property<string>("PasswordResetToken").HasColumnType("nvarchar(max)");
                    b.Property<string>("PasswordHash").HasColumnType("nvarchar(max)");
                    b.Property<string>("PasswordSalt").HasColumnType("nvarchar(max)");
                    b.Property<string>("ProfileImageUrl").HasColumnType("nvarchar(max)");
                    b.Property<string>("MemberCode").HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("WorkSchedule").HasMaxLength(100).HasColumnType("nvarchar(100)").HasDefaultValue("Default Work Schedule");
                    b.Property<string>("Role").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Employees");
                });

            modelBuilder.Entity("APM.StaffZen.API.Models.Organization", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<int>("EmployeeId").HasColumnType("int");
                    b.Property<string>("Country").HasColumnType("nvarchar(100)");
                    b.Property<string>("CountryCode").HasColumnType("nvarchar(20)");
                    b.Property<string>("Industry").HasColumnType("nvarchar(100)");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(256)");
                    b.Property<string>("OrganizationSize").HasColumnType("nvarchar(50)");
                    b.Property<string>("OwnerRole").HasColumnType("nvarchar(100)");
                    b.Property<string>("PhoneNumber").HasColumnType("nvarchar(50)");
                    b.HasKey("Id");
                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("APM.StaffZen.API.Models.EmployeeInvite", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Email").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("ExpiryDate").HasColumnType("datetime2");
                    b.Property<bool>("IsUsed").HasColumnType("bit");
                    b.Property<int>("OrganizationId").HasColumnType("int").HasDefaultValue(0);
                    b.Property<string>("OrgRole").IsRequired().HasColumnType("nvarchar(50)").HasDefaultValue("Employee");
                    b.Property<string>("Role").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Token").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("EmployeeInvites");
                });

            modelBuilder.Entity("APM.StaffZen.API.Models.EmployeeNotificationSettings", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("EmployeeId").HasColumnType("int");
                    b.Property<bool>("ReportsChannelEmail").HasDefaultValue(true).HasColumnType("bit");
                    b.Property<bool>("ReportsChannelWhatsApp").HasDefaultValue(false).HasColumnType("bit");
                    b.Property<bool>("ReportsChannelSms").HasDefaultValue(false).HasColumnType("bit");
                    b.Property<bool>("ReportsChannelPush").HasDefaultValue(false).HasColumnType("bit");
                    b.Property<bool>("RemindersChannelEmail").HasDefaultValue(true).HasColumnType("bit");
                    b.Property<bool>("RemindersChannelWhatsApp").HasDefaultValue(false).HasColumnType("bit");
                    b.Property<bool>("RemindersChannelSms").HasDefaultValue(false).HasColumnType("bit");
                    b.Property<bool>("RemindersChannelPush").HasDefaultValue(false).HasColumnType("bit");
                    b.Property<bool>("NotifDailyAttendance").HasDefaultValue(false).HasColumnType("bit");
                    b.Property<string>("DailyAttendanceTime").IsRequired().HasDefaultValue("9:00 am").HasColumnType("nvarchar(max)");
                    b.Property<string>("DailyAttendanceFreq").IsRequired().HasDefaultValue("everyday").HasColumnType("nvarchar(max)");
                    b.Property<bool>("NotifWeeklyActivity").HasDefaultValue(true).HasColumnType("bit");
                    b.Property<string>("WeeklyActivityDay").IsRequired().HasDefaultValue("Monday").HasColumnType("nvarchar(max)");
                    b.Property<bool>("NotifClockIn").HasDefaultValue(false).HasColumnType("bit");
                    b.Property<int>("ClockInMinutes").HasDefaultValue(5).HasColumnType("int");
                    b.Property<bool>("NotifClockOut").HasDefaultValue(false).HasColumnType("bit");
                    b.Property<int>("ClockOutMinutes").HasDefaultValue(5).HasColumnType("int");
                    b.Property<bool>("NotifEndBreak").HasDefaultValue(false).HasColumnType("bit");
                    b.Property<int>("EndBreakMinutes").HasDefaultValue(5).HasColumnType("int");
                    b.Property<bool>("NotifTimeClockStarts").HasDefaultValue(false).HasColumnType("bit");
                    b.Property<bool>("NotifTimeOffRequests").HasDefaultValue(true).HasColumnType("bit");
                    b.Property<bool>("SubProductUpdates").HasDefaultValue(false).HasColumnType("bit");
                    b.Property<bool>("SubPromotions").HasDefaultValue(false).HasColumnType("bit");
                    b.Property<bool>("SubUsageTracking").HasDefaultValue(false).HasColumnType("bit");
                    b.HasKey("Id");
                    b.HasIndex("EmployeeId").IsUnique();
                    b.ToTable("EmployeeNotificationSettings");
                });

            modelBuilder.Entity("APM.StaffZen.API.Models.Group", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedDate").HasColumnType("datetime2");
                    b.Property<string>("Description").HasColumnType("nvarchar(max)");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Groups");
                });

            modelBuilder.Entity("APM.StaffZen.API.Models.TimeEntry", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("ClockIn").HasColumnType("datetime2");
                    b.Property<DateTime?>("ClockOut").HasColumnType("datetime2");
                    b.Property<int>("EmployeeId").HasColumnType("int");
                    b.Property<bool>("IsManual").HasColumnType("bit").HasDefaultValue(false);
                    b.Property<bool>("IsHourEntry").HasColumnType("bit").HasDefaultValue(false);
                    b.Property<bool>("IsBreakEntry").HasColumnType("bit").HasDefaultValue(false);
                    b.Property<string>("WorkedHours").HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("EmployeeId");
                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("APM.StaffZen.API.Models.TimeEntryChangeLog", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Action").IsRequired().HasColumnType("nvarchar(50)");
                    b.Property<int>("EmployeeId").HasColumnType("int");
                    b.Property<DateTime>("ChangedAt").HasColumnType("datetime2");
                    b.Property<DateTime?>("NewClockIn").HasColumnType("datetime2");
                    b.Property<DateTime?>("NewClockOut").HasColumnType("datetime2");
                    b.Property<DateTime?>("OldClockIn").HasColumnType("datetime2");
                    b.Property<DateTime?>("OldClockOut").HasColumnType("datetime2");
                    b.Property<string>("ReasonForChange").HasColumnType("nvarchar(max)");
                    b.Property<int>("TimeEntryId").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("TimeEntryId");
                    b.ToTable("TimeEntryChangeLogs");
                });

            modelBuilder.Entity("APM.StaffZen.API.Models.OrganizationMember", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int").UseIdentityColumn();
                    b.Property<int>("OrganizationId").HasColumnType("int");
                    b.Property<int>("EmployeeId").HasColumnType("int");
                    b.Property<string>("OrgRole").IsRequired().HasColumnType("nvarchar(50)").HasDefaultValue("Employee");
                    b.Property<DateTime>("JoinedAt").HasColumnType("datetime2");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.HasKey("Id");
                    b.HasIndex(new[] { "OrganizationId", "EmployeeId" }).IsUnique();
                    b.ToTable("OrganizationMembers");
                });


            modelBuilder.Entity("APM.StaffZen.API.Models.WorkSchedule", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)").HasDefaultValue("New Schedule");
                    b.Property<bool>("IsDefault").HasColumnType("bit").HasDefaultValue(false);
                    b.Property<string>("Arrangement").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("Fixed");
                    b.Property<string>("WorkingDays").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)").HasDefaultValue("Mon,Tue,Wed,Thu,Fri");
                    b.Property<string>("DaySlotsJson").IsRequired().HasColumnType("nvarchar(max)").HasDefaultValue("{}");
                    b.Property<bool>("IncludeBeforeStart").HasColumnType("bit").HasDefaultValue(false);
                    b.Property<int>("WeeklyHours").HasColumnType("int").HasDefaultValue(0);
                    b.Property<int>("WeeklyMinutes").HasColumnType("int").HasDefaultValue(0);
                    b.Property<string>("SplitAt").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)").HasDefaultValue("00:00");
                    b.Property<string>("BreaksJson").IsRequired().HasColumnType("nvarchar(max)").HasDefaultValue("[]");
                    b.Property<string>("AutoDeductionsJson").IsRequired().HasColumnType("nvarchar(max)").HasDefaultValue("[]");
                    b.Property<bool>("DailyOvertime").HasColumnType("bit").HasDefaultValue(false);
                    b.Property<bool>("DailyOvertimeIsTime").HasColumnType("bit").HasDefaultValue(false);
                    b.Property<int>("DailyOvertimeAfterHours").HasColumnType("int").HasDefaultValue(8);
                    b.Property<int>("DailyOvertimeAfterMins").HasColumnType("int").HasDefaultValue(0);
                    b.Property<double>("DailyOvertimeMultiplier").HasColumnType("float").HasDefaultValue(1.5);
                    b.Property<bool>("DailyDoubleOvertime").HasColumnType("bit").HasDefaultValue(false);
                    b.Property<int>("DailyDoubleOTAfterHours").HasColumnType("int").HasDefaultValue(8);
                    b.Property<int>("DailyDoubleOTAfterMins").HasColumnType("int").HasDefaultValue(0);
                    b.Property<double>("DailyDoubleOTMultiplier").HasColumnType("float").HasDefaultValue(1.5);
                    b.Property<bool>("WeeklyOvertime").HasColumnType("bit").HasDefaultValue(false);
                    b.Property<int>("WeeklyOvertimeAfterHours").HasColumnType("int").HasDefaultValue(40);
                    b.Property<int>("WeeklyOvertimeAfterMins").HasColumnType("int").HasDefaultValue(0);
                    b.Property<double>("WeeklyOvertimeMultiplier").HasColumnType("float").HasDefaultValue(1.5);
                    b.Property<bool>("RestDayOvertime").HasColumnType("bit").HasDefaultValue(false);
                    b.Property<double>("RestDayOvertimeMultiplier").HasColumnType("float").HasDefaultValue(1.5);
                    b.Property<bool>("PublicHolidayOvertime").HasColumnType("bit").HasDefaultValue(false);
                    b.Property<double>("PublicHolidayOvertimeMultiplier").HasColumnType("float").HasDefaultValue(1.5);
                    b.Property<int?>("OrganizationId").HasColumnType("int");
                    b.HasKey("Id");
                    b.ToTable("WorkSchedules");
                });

            modelBuilder.Entity("APM.StaffZen.API.Models.Employee", b =>
                {
                    b.HasOne("APM.StaffZen.API.Models.Organization", "Organization")
                        .WithMany("Employees")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("Organization");
                });

            modelBuilder.Entity("APM.StaffZen.API.Models.Organization", b =>
                { b.Navigation("Employees"); });

            modelBuilder.Entity("APM.StaffZen.API.Models.OrganizationMember", b =>
                {
                    b.HasOne("APM.StaffZen.API.Models.Organization", "Organization")
                        .WithMany().HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("APM.StaffZen.API.Models.Employee", "Employee")
                        .WithMany().HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Organization");
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("APM.StaffZen.API.Models.TimeEntry", b =>
                {
                    b.HasOne("APM.StaffZen.API.Models.Employee", "Employee")
                        .WithMany().HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("APM.StaffZen.API.Models.TimeEntryChangeLog", b =>
                {
                    b.HasOne("APM.StaffZen.API.Models.TimeEntry", "TimeEntry")
                        .WithMany().HasForeignKey("TimeEntryId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("TimeEntry");
                });
#pragma warning restore 612, 618
        }
    }
}
